version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10
    logging:
      driver: none

  answers_reader:
    build:
      context: .
      dockerfile: answers_reader/Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - SENTIMENT_CALCULATOR_COUNT
    volumes:
      - ../data:/data

  point_a_sentiment_calculator:
    build:
      context: .
      dockerfile: point_a/sentiment_calculator/Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../nltk_data:/root/nltk_data

  point_a_percentage_calculator:
    build:
      context: .
      dockerfile: point_a/percentage_calculator/Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - SENTIMENT_CALCULATOR_COUNT
    volumes:
      - ../results:/results
